// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/consensus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsensusMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	View      uint32                 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Sequence  uint32                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	BlockHash string                 `protobuf:"bytes,4,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Sender    string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	// --- BLS FIELDS ---
	Signature     int64    `protobuf:"varint,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Signers       []string `protobuf:"bytes,7,rep,name=signers,proto3" json:"signers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessage) Reset() {
	*x = ConsensusMessage{}
	mi := &file_proto_consensus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessage) ProtoMessage() {}

func (x *ConsensusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessage.ProtoReflect.Descriptor instead.
func (*ConsensusMessage) Descriptor() ([]byte, []int) {
	return file_proto_consensus_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConsensusMessage) GetView() uint32 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ConsensusMessage) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ConsensusMessage) GetBlockHash() string {
	if x != nil {
		return x.BlockHash
	}
	return ""
}

func (x *ConsensusMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ConsensusMessage) GetSignature() int64 {
	if x != nil {
		return x.Signature
	}
	return 0
}

func (x *ConsensusMessage) GetSigners() []string {
	if x != nil {
		return x.Signers
	}
	return nil
}

// --- NEW TRANSACTION FIELDS ---
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_consensus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_consensus_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Transaction) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type TxAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxAck) Reset() {
	*x = TxAck{}
	mi := &file_proto_consensus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxAck) ProtoMessage() {}

func (x *TxAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxAck.ProtoReflect.Descriptor instead.
func (*TxAck) Descriptor() ([]byte, []int) {
	return file_proto_consensus_proto_rawDescGZIP(), []int{2}
}

func (x *TxAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TxAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_consensus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_consensus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_consensus_proto_rawDescGZIP(), []int{3}
}

var File_proto_consensus_proto protoreflect.FileDescriptor

const file_proto_consensus_proto_rawDesc = "" +
	"\n" +
	"\x15proto/consensus.proto\x12\x05proto\"\xc5\x01\n" +
	"\x10ConsensusMessage\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04view\x18\x02 \x01(\rR\x04view\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\rR\bsequence\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x04 \x01(\tR\tblockHash\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\x03R\tsignature\x12\x18\n" +
	"\asigners\x18\a \x03(\tR\asigners\"c\n" +
	"\vTransaction\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\tR\n" +
	"receiverId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\";\n" +
	"\x05TxAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\a\n" +
	"\x05Empty2\x7f\n" +
	"\x10ConsensusService\x124\n" +
	"\vSendMessage\x12\x17.proto.ConsensusMessage\x1a\f.proto.Empty\x125\n" +
	"\x11SubmitTransaction\x12\x12.proto.Transaction\x1a\f.proto.TxAckB\tZ\a./protob\x06proto3"

var (
	file_proto_consensus_proto_rawDescOnce sync.Once
	file_proto_consensus_proto_rawDescData []byte
)

func file_proto_consensus_proto_rawDescGZIP() []byte {
	file_proto_consensus_proto_rawDescOnce.Do(func() {
		file_proto_consensus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_consensus_proto_rawDesc), len(file_proto_consensus_proto_rawDesc)))
	})
	return file_proto_consensus_proto_rawDescData
}

var file_proto_consensus_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_consensus_proto_goTypes = []any{
	(*ConsensusMessage)(nil), // 0: proto.ConsensusMessage
	(*Transaction)(nil),      // 1: proto.Transaction
	(*TxAck)(nil),            // 2: proto.TxAck
	(*Empty)(nil),            // 3: proto.Empty
}
var file_proto_consensus_proto_depIdxs = []int32{
	0, // 0: proto.ConsensusService.SendMessage:input_type -> proto.ConsensusMessage
	1, // 1: proto.ConsensusService.SubmitTransaction:input_type -> proto.Transaction
	3, // 2: proto.ConsensusService.SendMessage:output_type -> proto.Empty
	2, // 3: proto.ConsensusService.SubmitTransaction:output_type -> proto.TxAck
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_consensus_proto_init() }
func file_proto_consensus_proto_init() {
	if File_proto_consensus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_consensus_proto_rawDesc), len(file_proto_consensus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_consensus_proto_goTypes,
		DependencyIndexes: file_proto_consensus_proto_depIdxs,
		MessageInfos:      file_proto_consensus_proto_msgTypes,
	}.Build()
	File_proto_consensus_proto = out.File
	file_proto_consensus_proto_goTypes = nil
	file_proto_consensus_proto_depIdxs = nil
}
